SIM_DIASCA_TOP = ../..


.PHONY: all

OVERALL_DOCUMENT_SOURCE = $(DEV_GUIDE)


# Default do-nothing target:
all:
	@echo "  Run 'make full-doc' to generate the "\
	"developer guide ($(DEV_GUIDE))."


# Root specified as we want to catch the doc in src/core as well:
#
DOCUTILS_TOP = $(SIM_DIASCA_TOP)


include $(SIM_DIASCA_TOP)/GNUmakesettings.inc
