#!/bin/bash

OLD_IFS=$IFS
IFS=","

echo "" > ${12}/app/sim-diasca/mock-simulators/city-example/src/sim-diasca-host-candidates-for-scale-benchmarks.txt
echo "" > ${12}/app/sim-diasca/mock-simulators/city-example/src/sim-diasca-host-candidates.txt

i=1
for node in ${5}; do

    if [[ "$i" -gt "${6}" ]]; then
        break;
    fi

    node=${node:1:-1}
    name=`echo $node | cut -d'@' -f1`
    host=`echo $node | cut -d'@' -f2`

    echo "'$host'." >>  ${12}/app/sim-diasca/mock-simulators/city-example/src/sim-diasca-host-candidates-for-scale-benchmarks.txt
    echo "'$host'." >> ${12}/app/sim-diasca/mock-simulators/city-example/src/sim-diasca-host-candidates.txt
 
    IFS=$OLD_IFS
    cmd="BENCHERL_ROOT=${12} ${10} ${11} ${3} -setcookie '${4}' +K true \
        +A 128 +P 1048576 +S${1}:${1} -sname $name -noshell -pa ${8} ${9} \
        ${12}/suite/ebin-${7} ${12}/bench/city-simulation/ebin-${7} \
        -kernel inet_dist_listen_min 50000 inet_dist_listen_max 55000"
    ssh -f `whoami`@$host "$cmd"
    IFS=","

    i=$((i+1))
    hosts="$hosts\n'$host'."

done

IFS=$OLD_IFS

