#!/bin/bash

if [ -z "$2" ]; then
	e1="erlc"
	e2="erl"
	e3="epmd"
else
	e1="$2/bin/erlc"
	e2="$2/bin/erl"
	e3="$2/x86_64-unknown-linux-gnu/epmd"
fi

env BEAMDIR="app/scalaris/ebin" ERLC="$e1" ERL="$e2" EPMD="$e3" app/scalaris/bin/firstnode.sh "+S$1:$1 -detached -noshell" &

sleep 3s 

