WOOPER_TOP = ..


include $(WOOPER_TOP)/GNUmakesettings.inc


# Helper modules (ex: bqasic_utils.beam, wooper_class_manager.beam, etc.) are
# not listed here as dependencies, their possible lacking will be detected at
# run-time.


wooper_class_manager_test: \
	wooper_class_manager_test.beam   \
	wooper_class_manager.beam


class_Wooper_attribute_test: \
	class_Wooper_attribute_test.beam \
	wooper_class_manager.beam
