#!/bin/bash

if [ -z "$2" ]; then
    e1="erl"
else
    e="$2/bin/erl"
fi

env ERL="$e1" RABBITMQ_MNESIA_BASE=scratch/mnesia RABBITMQ_LOG_BASE=scratch/log app/rabbitmq-server/scripts/rabbitmqctl stop > /dev/null 

