#!/bin/bash

if [ -z "$2" ]; then
	e1="erl"
else
	e1="$2/bin/erl"
fi

env RABBITMQ_CTL_ERL_ARGS="-name rabbit@`hostname -f` -setcookie $4" RABBITMQ_SERVER_ERL_ARGS="-name rabbit@`hostname -h` -setcookie $4" ERL="$e1" RABBITMQ_EBIN_ROOT="app/rabbitmq-server/ebin app/rabbitmq-server/plugins-src/rabbitmq-erlang-client/dist/amqp_client/ebin app/rabbitmq-server/plugins-src/rabbitmq-erlang-client/dist/rabbit_common/ebin" RABBITMQ_MNESIA_BASE=scratch/mnesia RABBITMQ_LOG_BASE=scratch/log app/rabbitmq-server/scripts/rabbitmq-server +S$1:$1 -detached 
#> /dev/null 

sleep 5s

