SIM_DIASCA_TOP = ../..


MODULES_DIRS = doc generic mesh space src


# No trace supervisor or graphical output wanted when running all tests from a
# root directory (batch mode vs interactive one):
CMD_LINE_OPT = "--batch"


include $(SIM_DIASCA_TOP)/GNUmakesettings.inc
