MOCK_SIMULATORS_TOP = ../..


.PHONY: all

OVERALL_DOCUMENT_SOURCE = City-Example-benchmarking-case.pdf


# Default do-nothing target:
all:
	@echo "  Run 'make full-doc' to generate the City-Example manual."


# Root specified as we want to catch the doc in src/core as well:
DOCUTILS_TOP = .


include $(MOCK_SIMULATORS_TOP)/GNUmakesettings.inc
